// Test the Pointer example using the WASM compiler
const fs = require('fs');
const path = require('path');

// The vixc-wasm.js generated by Emscripten
const wasmJsPath = path.join(__dirname, 'playground', 'vixc-wasm.js');
const wasmPath = path.join(__dirname, 'playground', 'vixc-wasm.wasm');

// Set up the Module for Emscripten
const wasmBinary = fs.readFileSync(wasmPath);

// Global log capture
let outputLines = [];

const Module = {
    wasmBinary: wasmBinary,
    arguments: [],
    print: function(text) {
        outputLines.push('print: ' + text);
        console.log('[STDOUT]', text);
    },
    printErr: function(text) {
        outputLines.push('err: ' + text);
        console.log('[STDERR]', text);
    },
    locateFile: function(file) {
        return path.join(__dirname, 'playground', file);
    },
    noInitialRun: true,
    onRuntimeInitialized: function() {
        console.log('WASM runtime initialized');

        const source = `fn main(): i32 {
    let x = 10
    let mut ptr = ref x
    @ptr = 20
    let arr = [1, 2, 3, 4, 5]
    let p = ref arr[0]
    let second = @(p + 1)
    print(second)
    return 0
}`;

        console.log('Compiling source...');
        const result = Module._compile_vix(source);
        console.log('compile result:', result);

        // The function writes to a shared buffer, read it
        const ptrOut = Module._get_ptr_out();
        const lenOut = Module._get_len_out();
        const errOut = Module._get_err_out();

        console.log('ptrOut:', ptrOut, 'lenOut:', lenOut, 'errOut:', errOut);

        if (lenOut > 0) {
            // Read the WASM bytes
            const wasmBytes = new Uint8Array(lenOut);
            for (let i = 0; i < lenOut; i++) {
                wasmBytes[i] = Module.HEAPU8[ptrOut + i];
            }
            console.log('Generated WASM:', lenOut, 'bytes');

            // Run the generated WASM
            const env = {
                vix_putchar: function(c) {
                    process.stdout.write(String.fromCharCode(c));
                },
                vix_puts: function(ptr) {
                    var mem = new Uint8Array(wasmInstance.exports.memory.buffer);
                    var s = '';
                    while (mem[ptr] !== 0) {
                        s += String.fromCharCode(mem[ptr]);
                        ptr++;
                    }
                    console.log('OUTPUT:', s);
                },
                vix_print_i32: function(value) {
                    console.log('OUTPUT:', value);
                },
                vix_exit: function(code) {
                    console.log('exit:', code);
                }
            };

            WebAssembly.instantiate(wasmBytes, { env })
            .then(({instance}) => {
                wasmInstance = instance;
                console.log('exports:', Object.keys(instance.exports));
                if (instance.exports.main) {
                    const result = instance.exports.main();
                    console.log('main returned:', result);
                    console.log('---TEST RESULT---');
                    if (outputLines.includes('OUTPUT: 2') || outputLines.includes('print: 2')) {
                        console.log('PASS: Output is 2 as expected');
                    } else {
                        console.log('FAIL: Expected output 2, got something else');
                    }
                }
            })
            .catch(err => {
                console.error('WASM run error:', err.message);
            });
        } else {
            // Read error
            const errStr = Module.UTF8ToString(errOut);
            console.log('Compilation error:', errStr);
            console.log('FAIL: Compilation failed');
        }
    }
};

// Load the Emscripten module
require(wasmJsPath);
